### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Helias** [azerothcore/mod-arena-replay#2]
~~- [ ] use LONGBLOB and convert buffer data into HEX~~
- [x] add enable/disable conf
- [x] conf: delete every X days the saved replay
- [ ] bug: when a player watches his game there is a reference bug

**Comment by heyitsbench** [comment]
Might want to add using `module_string` instead of the hardcoded strings so they can be localized.

**Comment by Helias** [comment]
> Might want to add using `module_string` instead of the hardcoded strings so they can be localized.

this is an improvement indeed, I could do that if I find the time

**Comment by Helias** [comment]
I will make separate issues and I will not do the longblob change, making some tries I did not succeed on it, I spent too much time on it so far
